# Usage

Welcome to your Alfresco Community {{.Version}} Docker Compose deployment!

Before executing this installer be sure that Docker is running in your computer. 

When Docker is up & ready, verify that 12 GB of Memory are available. 

## Starting Alfresco

Start Alfresco using the command `docker compose up`

Once the platform is ready, you will find a line similar to the following one in the terminal:
```
alfresco-1 | org.apache.catalina.startup.Catalina.start Server startup in [NNNNN] milliseconds
```

## Service URLs

   * UI: http://{{.Server}}:8080/
{{- if eq .LegacyUI "Yes"}}
   * Legacy UI: http://{{.Server}}:8080/share
{{- end}}   
   * Repository (REST API): http://{{.Server}}:8080/alfresco
{{- if eq .Messaging "Yes"}}
   * ActiveMQ (Messaging API): tcp://{{.Server}}:61616
{{- end}}   

Remember to use following credentials:

   * username: admin
   * password: admin

## Container Persistence and Storage

"{{.Volumes}}" volumes has been selected.

{{if eq .Volumes "None" -}}
Data generated by the containers is not persisted in Docker Volumes.
Once containers are destroyed, stored data will be lost.
{{- end}}

{{- if eq .Volumes "Bind"}}
Data generated by the containers is persisted in mounted Docker Volumes.
You may need to tweak permissions for create local folders `data` and `logs`,
since different containers are being run with a different users.
{{- end}}

{{- if eq .Volumes "Native"}}
Data generated by the containers is persisted in Docker Volumes.
Store information can be managed by using `docker volume` commands.
{{- end}}

## Stopping

Alfresco can be stopped typing `Ctrl+C` in the terminal used to start the Docker Compose.

If you want to start again Alfresco, type `docker compose up` from the folder used to produce the configuration.